# Generated by Django 4.2.18 on 2025-01-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('sparepart', '0002_sparepart_category_sparepart_condition_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sparepart',
            name='sparepart_s_year_3e083a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sparepart',
            name='sparepart_s_make_c9589e_idx',
        ),
        migrations.RemoveIndex(
            model_name='sparepart',
            name='sparepart_s_created_f12a81_idx',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='part_number',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subparts', to='category.category'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='category.category'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
