# Generated by Django 4.2.18 on 2025-02-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_remove_sparepart_sparepart_s_year_3e083a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sparepart_images/')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sparepart.sparepart')),
            ],
        ),
    ]
