# Generated by Django 4.2.18 on 2025-04-04 14:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0004_sparepartimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
